spring:
  datasource:
    url: jdbc:h2:mem:pizzadb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  #jpa:
  #  hibernate:
  #    ddl-auto: create
  #  show-sql: true
    # properties:
    #   hibernate:
    #     format_sql: true
  sql:
    init:
      mode: always   # executa schema.sql no boot
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  h2:
    console:
      enabled: true
      path: /h2
logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
    com:
      bcopstein: DEBUG
application:
  name: ex4-lancheriaddd-v1
server:
  port: 8080